# Generated by Django 5.2.14 on 2026-05-31 04:42

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(help_text='Ej.: 2026', unique=True, verbose_name='Año')),
                ('activo', models.BooleanField(default=True, help_text='Solo los años activos se muestran en la web pública.', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Año académico',
                'verbose_name_plural': 'Años académicos',
                'db_table': 'ANIOS',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej.: 6°A', max_length=40, verbose_name='Nombre')),
                ('nivel', models.CharField(blank=True, help_text="Opcional. Ej.: 'Secundaria'.", max_length=40, verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'CURSOS',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=160, verbose_name='Título')),
                ('archivo', models.FileField(db_column='RUTA_ARCHIVO', upload_to='galeria/', validators=[core.validators.validar_imagen], verbose_name='Imagen')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Imágenes de galería',
                'db_table': 'IMAGENES',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('cuerpo', models.TextField(verbose_name='Cuerpo')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('activo', models.BooleanField(default=True, help_text='Solo las noticias activas aparecen en la web.', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'db_table': 'NOTICIAS',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.SlugField(help_text='Identificador interno. Ej.: mision, vision, contacto.', max_length=60, unique=True, verbose_name='Clave')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Sección de texto',
                'verbose_name_plural': 'Secciones de texto',
                'db_table': 'SECCIONES',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('youtube_url', models.URLField(help_text='Pega el enlace normal de YouTube; se embebe solo.', verbose_name='Enlace de YouTube')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'VIDEOS',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='core.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'MATERIAS',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('archivo', models.FileField(db_column='RUTA_ARCHIVO', upload_to='guias/', validators=[core.validators.validar_pdf], verbose_name='Archivo PDF')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='core.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Guía de estudio',
                'verbose_name_plural': 'Guías de estudio',
                'db_table': 'GUIAS',
                'ordering': ['-fecha_publicacion', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Del 1 al 4.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Número')),
                ('nombre', models.CharField(blank=True, help_text="Opcional. Ej.: 'Primer período'.", max_length=60, verbose_name='Nombre')),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='core.anio', verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'db_table': 'PERIODOS',
                'ordering': ['anio', 'numero'],
                'unique_together': {('anio', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='core.periodo', verbose_name='Período'),
        ),
    ]
