# Generated by Django 5.2.14 on 2026-05-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ['categoria', 'orden', 'clave'], 'verbose_name': 'Sección de texto', 'verbose_name_plural': 'Secciones de texto'},
        ),
        migrations.AddField(
            model_name='seccion',
            name='categoria',
            field=models.CharField(choices=[('home', 'Inicio (identidad)'), ('colegio', 'El Colegio'), ('proyecto', 'Proyectos')], default='home', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden dentro de su categoría.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='clave',
            field=models.SlugField(help_text='Identificador interno. Ej.: mision, vision, prae.', max_length=60, unique=True, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='contenido',
            field=models.TextField(blank=True, verbose_name='Contenido'),
        ),
    ]
