# Generated by Django 5.2.14 on 2026-06-16 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_seccion_options_seccion_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'ordering': ['seccion__orden', 'orden', '-fecha'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
        migrations.AddField(
            model_name='imagen',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='seccion',
            field=models.ForeignKey(blank=True, help_text='Sección a la que pertenece (vacío = galería general de la home).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes', to='core.seccion', verbose_name='Sección'),
        ),
    ]
