# Generated by Django 5.2.14 on 2026-06-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_imagen_options_imagen_orden_imagen_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('archivo', models.FileField(db_column='RUTA_ARCHIVO', upload_to='documentos/', verbose_name='Archivo')),
                ('categoria', models.CharField(choices=[('guia', 'Guía SERC'), ('circular', 'Circular'), ('cronograma', 'Cronograma'), ('horario', 'Horario'), ('formato', 'Formato'), ('manual', 'Manual / Institucional'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría')),
                ('anio', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos (circulares, guías…)',
                'db_table': 'DOCUMENTOS',
                'ordering': ['categoria', '-anio', 'orden', 'titulo'],
            },
        ),
    ]
