# Generated by Django 5.2.14 on 2026-06-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['categoria', '-anio', 'nivel', 'periodo', 'area', 'orden', 'titulo'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos (circulares, guías…)'},
        ),
        migrations.AddField(
            model_name='documento',
            name='area',
            field=models.CharField(blank=True, max_length=80, verbose_name='Área / materia'),
        ),
        migrations.AddField(
            model_name='documento',
            name='grado',
            field=models.CharField(blank=True, help_text='Ej.: 9°, 1º, Transición. En bachillerato suele ir en el título.', max_length=20, verbose_name='Grado'),
        ),
        migrations.AddField(
            model_name='documento',
            name='nivel',
            field=models.CharField(blank=True, choices=[('preescolar', 'Preescolar'), ('primaria', 'Primaria'), ('bachillerato', 'Bachillerato')], max_length=12, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='documento',
            name='periodo',
            field=models.CharField(blank=True, choices=[('I', 'I Período'), ('II', 'II Período'), ('III', 'III Período'), ('IV', 'IV Período')], max_length=3, verbose_name='Período'),
        ),
    ]
