# Generated by Django 5.2.14 on 2026-06-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_documento_options_documento_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(db_column='RUTA_ARCHIVO', max_length=255, upload_to='documentos/', verbose_name='Archivo'),
        ),
    ]
