# Generated by Django 5.2.14 on 2026-06-16 16:13

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='archivo',
            field=models.FileField(db_column='RUTA_ARCHIVO', max_length=255, upload_to='guias/', validators=[core.validators.validar_pdf], verbose_name='Archivo PDF'),
        ),
    ]
