# Generated by Django 5.2.14 on 2026-10-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_guia_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionApariencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_principal', models.CharField(default='#0a1931', help_text='Color hex para la barra superior, botones y títulos principales. Ej: #0a1931', max_length=18, verbose_name='Color Principal (Cabecera/Títulos)')),
                ('color_secundario', models.CharField(default='#15305b', help_text='Color hex para la barra del menú principal. Ej: #15305b', max_length=18, verbose_name='Color Secundario (Menú Principal)')),
                ('color_acento', models.CharField(default='#c5a880', help_text='Color de acento para líneas divisoras y botones destacados. Ej: #c5a880', max_length=18, verbose_name='Color de Acento (Bordes/Destacados)')),
                ('color_acento_suave', models.CharField(default='#e5d5be', help_text='Color claro para detalles secundarios. Ej: #e5d5be', max_length=18, verbose_name='Color de Acento Suave')),
                ('color_footer', models.CharField(default='#0b6d71', help_text='Color para el pie de página. Ej: #0b6d71', max_length=18, verbose_name='Color del Pie de Página (Footer)')),
                ('color_texto', models.CharField(default='#0f172a', help_text='Color oscuro para textos principales. Ej: #0f172a', max_length=18, verbose_name='Color de Texto Principal')),
            ],
            options={
                'verbose_name': 'Apariencia y Colores del Sitio',
                'verbose_name_plural': 'Apariencia y Colores del Sitio',
                'db_table': 'CONFIGURACION_APARIENCIA',
            },
        ),
    ]
