-- ===========================================================================
--  Athena — Esquema Oracle (referencia)
-- ===========================================================================
--  Jerarquía de guías:  AÑO → PERÍODO (1–4) → CURSO → MATERIA → GUÍAS
--
--  IMPORTANTE: en este proyecto la fuente de verdad del esquema es Django.
--  En producción las tablas se crean con:   python manage.py migrate
--  Este archivo documenta el esquema equivalente en Oracle y sirve para
--  revisión por un DBA. Las columnas y nombres coinciden con los modelos de
--  core/models.py (Meta.db_table en MAYÚSCULAS).
--
--  La base guarda SOLO datos y la RUTA del archivo (RUTA_ARCHIVO). El archivo
--  pesado vive en Object Storage, NO en la base.
--
--  USUARIOS (login del rector) lo gestiona Django (tablas auth_*); no se crea
--  a mano aquí.
-- ===========================================================================

-- --- AÑO ---------------------------------------------------------------
CREATE TABLE ANIOS (
    id      NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio    NUMBER(10)   NOT NULL,
    activo  NUMBER(1)    DEFAULT 1 NOT NULL,
    CONSTRAINT uq_anios_anio UNIQUE (anio),
    CONSTRAINT ck_anios_activo CHECK (activo IN (0, 1))
);

-- --- PERÍODO (1–4), pertenece a un AÑO ---------------------------------
CREATE TABLE PERIODOS (
    id       NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio_id  NUMBER(19)    NOT NULL,
    numero   NUMBER(5)     NOT NULL,
    nombre   VARCHAR2(60)  DEFAULT NULL,
    CONSTRAINT fk_periodos_anio FOREIGN KEY (anio_id) REFERENCES ANIOS (id),
    CONSTRAINT uq_periodos_anio_num UNIQUE (anio_id, numero),
    CONSTRAINT ck_periodos_numero CHECK (numero BETWEEN 1 AND 4)
);

-- --- CURSO, pertenece a un PERÍODO -------------------------------------
CREATE TABLE CURSOS (
    id          NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periodo_id  NUMBER(19)    NOT NULL,
    nombre      VARCHAR2(40)  NOT NULL,
    nivel       VARCHAR2(40)  DEFAULT NULL,
    CONSTRAINT fk_cursos_periodo FOREIGN KEY (periodo_id) REFERENCES PERIODOS (id)
);

-- --- MATERIA, pertenece a un CURSO -------------------------------------
CREATE TABLE MATERIAS (
    id        NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id  NUMBER(19)    NOT NULL,
    nombre    VARCHAR2(80)  NOT NULL,
    CONSTRAINT fk_materias_curso FOREIGN KEY (curso_id) REFERENCES CURSOS (id)
);

-- --- GUÍA (PDF), pertenece a una MATERIA -------------------------------
--  RUTA_ARCHIVO guarda la ruta/URL del PDF en Object Storage (no el archivo).
CREATE TABLE GUIAS (
    id                 NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    materia_id         NUMBER(19)     NOT NULL,
    titulo             VARCHAR2(160)  NOT NULL,
    descripcion        CLOB           DEFAULT NULL,
    RUTA_ARCHIVO       VARCHAR2(255)  NOT NULL,
    fecha_publicacion  DATE           NOT NULL,
    CONSTRAINT fk_guias_materia FOREIGN KEY (materia_id) REFERENCES MATERIAS (id)
);

-- --- NOTICIAS (independiente) ------------------------------------------
CREATE TABLE NOTICIAS (
    id                 NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo             VARCHAR2(160)  NOT NULL,
    cuerpo             CLOB           NOT NULL,
    fecha_publicacion  TIMESTAMP      NOT NULL,
    activo             NUMBER(1)      DEFAULT 1 NOT NULL,
    CONSTRAINT ck_noticias_activo CHECK (activo IN (0, 1))
);

-- --- VIDEOS (links de YouTube, independiente) --------------------------
CREATE TABLE VIDEOS (
    id           NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo       VARCHAR2(160)  NOT NULL,
    youtube_url  VARCHAR2(200)  NOT NULL,
    descripcion  CLOB           DEFAULT NULL,
    fecha        DATE           NOT NULL
);

-- --- SECCIONES (textos editables de la home, independiente) ------------
CREATE TABLE SECCIONES (
    id         NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave      VARCHAR2(60)   NOT NULL,
    titulo     VARCHAR2(160)  NOT NULL,
    contenido  CLOB           NOT NULL,
    CONSTRAINT uq_secciones_clave UNIQUE (clave)
);

-- --- IMÁGENES (galería, independiente) ---------------------------------
--  RUTA_ARCHIVO guarda la ruta/URL de la imagen en Object Storage.
CREATE TABLE IMAGENES (
    id            NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo        VARCHAR2(160)  DEFAULT NULL,
    RUTA_ARCHIVO  VARCHAR2(255)  NOT NULL,
    fecha         DATE           NOT NULL
);

-- Índices útiles para la navegación pública por jerarquía.
CREATE INDEX ix_periodos_anio   ON PERIODOS (anio_id);
CREATE INDEX ix_cursos_periodo  ON CURSOS   (periodo_id);
CREATE INDEX ix_materias_curso  ON MATERIAS (curso_id);
CREATE INDEX ix_guias_materia   ON GUIAS    (materia_id);
